import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";

// The manual lists the body as 55.5 x 47.5 x 7.8 mm. The snap-on battery
// module covers the back; its thickness is estimated from product photos.
// The two buttons sit low on the front face; inside is simplified.

const ID = "aipi-lite";
const outer = outerFor(ID);
const BODY_T = 7.8;
const bodyCenterZ = outer.t / 2 - BODY_T / 2;

export const aipiLite: BoardModel = {
  deviceId: ID,
  name: "AIPI Lite",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 5,
  parts: [
    {
      id: "button-right",
      name: "Right button (talk)",
      kind: "button",
      shape: "cylinder",
      size: [4, 4, 1.8],
      position: [10, -16, 6],
      color: COLORS.caseBlack,
      finish: "rubber",
      explode: [0, 0, 48],
      approx: true,
      lesson: "The bottom-right button is push-to-talk under Muse. It also confirms pairing.",
    },
    {
      id: "button-left",
      name: "Left button (menu)",
      kind: "button",
      shape: "cylinder",
      size: [4, 4, 1.8],
      position: [-10, -16, 6],
      color: COLORS.caseBlack,
      finish: "rubber",
      explode: [0, 0, 48],
      approx: true,
      lesson: "The other button steps through the menu.",
    },
    {
      id: "front-case",
      name: "Front case",
      kind: "shell-front",
      shape: "roundedBox",
      radius: 5,
      hollow: { wall: 1.6, floor: "front" },
      size: [55.5, 47.5, BODY_T],
      position: [0, 0, bodyCenterZ],
      cutouts: [
        { shape: "rect", size: [27, 27], offset: [0, 3], radius: 1.5 },
        { shape: "circle", size: [4.4, 4.4], offset: [-10, -16] },
        { shape: "circle", size: [4.4, 4.4], offset: [10, -16] },
      ],
      color: COLORS.blueCase,
      finish: "plastic",
      explode: [0, 0, 38],
      lesson: "The front case comes in five colours. It has magnets inside.",
    },
    {
      id: "lcd",
      name: "128 x 128 color LCD",
      kind: "screen",
      shape: "box",
      size: [26, 26, 1.5],
      position: [0, 3, 4.55],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 26],
      approx: true,
      lesson: "A 128 by 128 pixel color LCD. Muse shows its full UI here: avatar, menu and images.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-19, -9, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 12],
      approx: true,
      lesson: LESSONS.esp32s3 + " Here it has 16 MB of flash and 8 MB of PSRAM.",
    },
    {
      id: "mic",
      name: "Microphone",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [19, -12, 3.3],
      color: COLORS.mic,
      explode: [0, 0, 12],
      approx: true,
      lesson: "A single microphone for push-to-talk.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 3,
      size: [50, 42, 1.2],
      position: [0, 0, 2.2],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 4],
      approx: true,
      lesson: "The main board inside the case. The screen, buttons, microphone and speaker all connect here.",
    },
    {
      id: "speaker",
      name: "Speaker",
      kind: "speaker",
      shape: "cylinder",
      size: [15, 15, 2.4],
      position: [16, 6, 0.4],
      color: COLORS.speaker,
      explode: [0, 0, -8],
      approx: true,
      lesson: "A small speaker. Muse replies come back as text unless you add your own text-to-speech.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [0, -20.1, 2.2],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -12, 0],
      approx: true,
      lesson: "USB-C for power and data. The snap-on battery module plugs into it too.",
    },
    {
      id: "battery",
      name: "Battery module (450 mAh)",
      kind: "battery",
      shape: "roundedBox",
      radius: 5,
      size: [55.5, 47.5, outer.t - BODY_T],
      position: [0, 0, -BODY_T / 2],
      color: "#efece2",
      finish: "plastic",
      explode: [0, 0, -26],
      approx: true,
      lesson: "The 450 mAh battery module snaps onto the back. It comes in the box, but a USB-C cable does not.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
