import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";

// Square puck that sits flat: +z is the top face with the dial, the centre
// button and the LED ring. +y is the far (rear) wall with USB-C and the
// 3.5 mm jack, per the catalog note. Inside is simplified.

const ID = "home-assistant-voice-pe";
const outer = outerFor(ID);

export const homeAssistantVoicePe: BoardModel = {
  deviceId: ID,
  name: "Home Assistant Voice Preview Edition",
  outer: { ...outer, shape: "box" },
  orientation: "flat",
  cornerRadius: 10,
  parts: [
    {
      id: "center-button",
      name: "Center button (talk)",
      kind: "button",
      shape: "cylinder",
      size: [22, 22, 2.5],
      position: [0, 0, 9.25],
      color: COLORS.caseWhite,
      finish: "plastic",
      explode: [0, 0, 66],
      lesson:
        "Hold the center button to talk to Muse. With the mute switch on, it goes back to setup duty: pairing and the 5 second reset.",
    },
    {
      id: "dial",
      name: "Rotary dial",
      kind: "button",
      shape: "cylinder",
      hollow: { wall: 8.5, floor: "none" },
      size: [47, 47, 2.5],
      position: [0, 0, 9.25],
      color: "#cfd1ce",
      finish: "plastic",
      explode: [0, 0, 56],
      lesson:
        "Turn the dial to set the speaker volume under Muse. The LED ring shows the level, and it is kept across restarts.",
    },
    {
      id: "top-cover",
      name: "Top cover",
      kind: "shell-front",
      shape: "roundedBox",
      radius: 10,
      size: [84, 84, 2.5],
      position: [0, 0, 9.25],
      cutouts: [{ shape: "circle", size: [48, 48] }],
      color: COLORS.caseWhite,
      finish: "plastic",
      explode: [0, 0, 36],
      lesson: "The top cover. Its round opening holds the dial and the center button.",
    },
    {
      id: "led-ring",
      name: "LED ring (12 LEDs)",
      kind: "led",
      shape: "cylinder",
      hollow: { wall: 3, floor: "none" },
      size: [29.4, 29.4, 1.6],
      position: [0, 0, 8.8],
      color: "#9fe3ff",
      glow: "#3fbfff",
      explode: [0, 0, 46],
      lesson: "Twelve LEDs in a ring show Muse status: orange for setup, blue for pairing and green when connected.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-27, -27, 6.7],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 18],
      approx: true,
      lesson:
        "The ESP32-S3 runs Muse, with 16 MB of flash and 8 MB of PSRAM. Flashing Muse replaces ESPHome on this chip only; reflash ESPHome to go back.",
    },
    {
      id: "xmos",
      name: "XMOS XU316 audio chip",
      kind: "chip",
      shape: "box",
      size: [8, 8, 1],
      position: [27, -27, 6.7],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 18],
      approx: true,
      lesson: "The XMOS XU316 processes audio from the microphones. It keeps its own firmware; never reflash it.",
    },
    {
      id: "mic-left",
      name: "Microphone (left)",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [-36, 0, 6.7],
      color: COLORS.mic,
      explode: [0, 0, 18],
      approx: true,
      lesson: "One of two microphones. Holding the center button records a voice note that Muse answers in the app.",
    },
    {
      id: "mic-right",
      name: "Microphone (right)",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [36, 0, 6.7],
      color: COLORS.mic,
      explode: [0, 0, 18],
      approx: true,
      lesson: "The second microphone of the pair. The XMOS chip works with both.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 8,
      size: [78, 78, 1.6],
      position: [0, 0, 5.4],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 8],
      approx: true,
      lesson: "The main board carries both chips, the two microphones and the ring of LEDs.",
    },
    {
      id: "speaker",
      name: "Speaker",
      kind: "speaker",
      shape: "cylinder",
      size: [40, 40, 9],
      position: [0, 0, -1.5],
      color: COLORS.speaker,
      explode: [0, 0, -14],
      approx: true,
      lesson:
        "The internal speaker. Muse replies arrive as text in the app; spoken replies need your own text-to-speech hook.",
    },
    {
      id: "mute-switch",
      name: "Mute switch",
      kind: "button",
      shape: "box",
      size: [3, 8, 3.5],
      position: [40.5, 10, 2],
      color: COLORS.rubber,
      finish: "rubber",
      explode: [16, 0, 0],
      approx: true,
      lesson: "A hardware switch that mutes the microphones.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [-10, 38.35, 0],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, 16, 0],
      lesson:
        "USB-C for power and flashing. It needs a 5 V 2 A supply, and flashing goes through the ESP32-S3's own USB port.",
    },
    {
      id: "audio-jack",
      name: "3.5 mm audio jack",
      kind: "port",
      shape: "cylinder",
      axis: "y",
      size: [6, 12, 6],
      position: [10, 36, 0],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, 16, 0],
      lesson: "A 3.5 mm audio output for a bigger speaker.",
    },
    {
      id: "grove",
      name: "Grove port",
      kind: "port",
      shape: "box",
      size: [8, 5, 5],
      position: [26, 39, 0],
      color: COLORS.caseWhite,
      explode: [0, 16, 0],
      approx: true,
      lesson: "A Grove port for add-on sensors.",
    },
    {
      id: "base",
      name: "Base",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 10,
      hollow: { wall: 2, floor: "back" },
      size: [84, 84, 18.5],
      position: [0, 0, -1.25],
      color: COLORS.caseLight,
      finish: "plastic",
      explode: [0, 0, -30],
      lesson: "The base of the puck. Home Assistant calls the Voice PE fully open software, firmware and hardware.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museEsp32Agents, FACT_SOURCES.museDevices]),
};
