import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";

// Bare PCB with the 1.9" LCD on the front and pin headers along both long
// edges. Only the outline and the display's active area are published, so
// the chip positions on the back are simplified guesses.

const ID = "ideaspark-esp32-1-9-lcd";
const outer = outerFor(ID);

export const ideasparkEsp32Lcd: BoardModel = {
  deviceId: ID,
  name: 'ideaspark ESP32 with 1.9" LCD',
  outer: { ...outer, shape: "board" },
  orientation: "upright",
  parts: [
    {
      id: "glass",
      name: "LCD cover glass",
      kind: "glass",
      shape: "box",
      size: [26.5, 47, 0.6],
      position: [0, 4.5, 6.5],
      color: COLORS.glass,
      finish: "glass",
      explode: [0, 0, 36],
      approx: true,
      lesson: "A thin glass layer over the LCD. There is no touch layer on this board.",
    },
    {
      id: "lcd",
      name: '1.9" color LCD',
      kind: "screen",
      shape: "box",
      size: [26.5, 47, 2.9],
      position: [0, 4.5, 4.75],
      color: COLORS.screenOff,
      finish: "screen",
      display: "status",
      explode: [0, 0, 24],
      lesson:
        "A 1.9 inch color LCD, 170 by 320 pixels, driven by an ST7789 controller. Muse shows status and draws images straight to it.",
    },
    {
      id: "pcb",
      name: "Circuit board",
      kind: "pcb",
      shape: "box",
      size: [31.5, 63.8, 1.6],
      position: [0, 0, 2.5],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 0],
      lesson: "A bare circuit board with no case. The screen, the chips and the pins all sit on this one board.",
    },
    {
      id: "boot-button",
      name: "BOOT button",
      kind: "button",
      shape: "box",
      size: [4, 3, 1.6],
      position: [10.5, -22, 4.1],
      color: COLORS.rubber,
      finish: "rubber",
      explode: [0, 0, 12],
      approx: true,
      lesson: "Press BOOT to confirm pairing. Hold it for 5 seconds to reset setup.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [0, -28.25, 4.9],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -12, 6],
      approx: true,
      lesson: LESSONS.usbData,
    },
    {
      id: "esp32",
      name: "ESP32 chip (D0WD-V3)",
      kind: "chip",
      shape: "box",
      size: [5, 5, 0.9],
      position: [0, 6, 1.25],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, -12],
      approx: true,
      lesson:
        "A classic ESP32: two cores at 240 MHz with Wi-Fi and Bluetooth. It has no PSRAM, so there is no home-network tunnel, but Muse can still reach and control it.",
    },
    {
      id: "flash",
      name: "16 MB flash memory",
      kind: "chip",
      shape: "box",
      size: [5.3, 5.3, 1.6],
      position: [-9, 6, 0.9],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, -12],
      approx: true,
      lesson: "16 MB of flash memory holds the Muse firmware.",
    },
    {
      id: "usb-serial",
      name: "CH340 USB-to-serial chip",
      kind: "chip",
      shape: "box",
      size: [6, 10, 1.6],
      position: [0, -16, 0.9],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, -12],
      approx: true,
      lesson:
        "The CH340 turns USB into a serial port for flashing. It shows up as /dev/cu.usbserial-*, /dev/cu.wchusbserial* or /dev/ttyUSB*.",
    },
    {
      id: "header-left",
      name: "Pin header (left)",
      kind: "port",
      shape: "box",
      size: [2.54, 48.26, 8.5],
      position: [-14.48, 0, -2.55],
      color: COLORS.header,
      explode: [-6, 0, -24],
      approx: true,
      lesson: "A row of pins along the long edge for jumper wires or a breadboard.",
    },
    {
      id: "header-right",
      name: "Pin header (right)",
      kind: "port",
      shape: "box",
      size: [2.54, 48.26, 8.5],
      position: [14.48, 0, -2.55],
      color: COLORS.header,
      explode: [6, 0, -24],
      approx: true,
      lesson: "The second row of pins. Muse only needs the USB cable, so the pins are free for your own wiring.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
