import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import { printedStandPart } from "../stand";
import type { BoardModel } from "../types";

// 48 x 24 x 15 mm stick with R3 corners (M5Stack drawing). Screen and the
// front button on the face, side button on the right, power on the left,
// Hat2 header and IR on top, USB-C and HY2.0 on the bottom.

const ID = "m5stack-sticks3";
const outer = outerFor(ID);

export const m5StickS3: BoardModel = {
  deviceId: ID,
  name: "M5Stack StickS3",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 3,
  parts: [
    {
      id: "front-button",
      name: "Front button (talk)",
      kind: "button",
      shape: "roundedBox",
      radius: 1.2,
      size: [8.4, 3.2, 2],
      position: [0, -12.5, 6.5],
      color: COLORS.blueButton,
      finish: "rubber",
      explode: [0, 0, 44],
      lesson: "The front button is push-to-talk under Muse. It also confirms pairing.",
    },
    {
      id: "front-plate",
      name: "Front of the case",
      kind: "shell-front",
      shape: "roundedBox",
      radius: 3,
      size: [24, 48, 2.5],
      position: [0, 0, 6.25],
      cutouts: [
        { shape: "rect", size: [15.5, 26.5], offset: [0, 7], radius: 1 },
        { shape: "rect", size: [9, 3.8], offset: [0, -12.5], radius: 1.5 },
      ],
      color: COLORS.caseDark,
      finish: "plastic",
      explode: [0, 0, 34],
      lesson: "The front of the case, with windows for the screen and the front button.",
    },
    {
      id: "lcd",
      name: '1.14" color LCD',
      kind: "screen",
      shape: "box",
      size: [14.2, 25.2, 1.4],
      position: [0, 7, 4.3],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 24],
      lesson:
        "A 1.14 inch color LCD, 135 by 240 pixels, driven by an ST7789P3. Muse shows its avatar, menu and images here.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3-PICO-1-N8R8",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-4, -15, 2.5],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 13],
      approx: true,
      lesson:
        "The ESP32-S3-PICO-1-N8R8: two cores at 240 MHz with 8 MB of flash and 8 MB of PSRAM in one package. The PSRAM is what lets Muse show images and run the home-network tunnel.",
    },
    {
      id: "codec",
      name: "ES8311 audio codec",
      kind: "chip",
      shape: "box",
      size: [4, 4, 1],
      position: [5, -15, 2.5],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 13],
      approx: true,
      lesson: "The ES8311 audio codec connects the microphone and the speaker to the ESP32-S3.",
    },
    {
      id: "imu",
      name: "Motion sensor (IMU)",
      kind: "sensor",
      shape: "box",
      size: [3, 3, 1],
      position: [6, -20.5, 2.5],
      color: COLORS.sensor,
      explode: [0, 0, 13],
      approx: true,
      lesson: "A motion sensor (IMU). Muse does not use it yet.",
    },
    {
      id: "mic",
      name: "Microphone",
      kind: "mic",
      shape: "cylinder",
      size: [2.5, 2.5, 1],
      position: [-5, -21, 2.5],
      color: COLORS.mic,
      explode: [0, 0, 13],
      approx: true,
      lesson: "A MEMS microphone for push-to-talk.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 2,
      size: [21.5, 45, 1],
      position: [0, 0, 1.5],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 4],
      approx: true,
      lesson: "The main board inside the stick. The chips sit below the screen.",
    },
    {
      id: "ir-tx",
      name: "IR transmitter",
      kind: "led",
      shape: "box",
      size: [3, 3, 2.4],
      position: [-5, 22.5, 3.5],
      color: "#2b2b30",
      glow: "#ff5a5a",
      explode: [0, 12, 0],
      approx: true,
      lesson: "An infrared transmitter for remote-control codes. Muse does not use it yet.",
    },
    {
      id: "ir-rx",
      name: "IR receiver",
      kind: "sensor",
      shape: "box",
      size: [3, 3, 2.4],
      position: [5, 22.5, 3.5],
      color: COLORS.sensor,
      explode: [0, 12, 0],
      approx: true,
      lesson: "An infrared receiver. Muse does not use it yet.",
    },
    {
      id: "hat-header",
      name: "Hat2 header (16-pin)",
      kind: "port",
      shape: "box",
      size: [20.3, 4, 5.1],
      position: [0, 22, -2.5],
      color: COLORS.header,
      explode: [0, 14, 0],
      lesson: "A 16-pin header on top for M5Stack Hat add-ons.",
    },
    {
      id: "speaker",
      name: "Speaker (1 W)",
      kind: "speaker",
      shape: "roundedBox",
      radius: 2,
      size: [12, 14, 3.5],
      position: [0, 12, -0.75],
      color: COLORS.speaker,
      explode: [0, 0, -10],
      approx: true,
      lesson: "A 1 W speaker. On battery alone, M5Stack suggests keeping the volume under 75% to avoid reboots.",
    },
    {
      id: "battery",
      name: "Battery (250 mAh)",
      kind: "battery",
      shape: "roundedBox",
      radius: 1.5,
      size: [20, 20, 4.5],
      position: [0, -5, -3.75],
      color: COLORS.battery,
      finish: "metal",
      explode: [0, 0, -18],
      approx: true,
      lesson: "A 250 mAh battery. Muse shows its charge level on screen.",
    },
    {
      id: "side-button",
      name: "Side button (menu)",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [1.6, 7, 3],
      position: [11.2, 6, 0],
      color: COLORS.rubber,
      finish: "rubber",
      explode: [12, 0, 0],
      approx: true,
      lesson: "The side button steps through the menu.",
    },
    {
      id: "power-button",
      name: "Power button",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [1.6, 7, 3],
      position: [-11.2, -12, 0],
      color: COLORS.rubber,
      finish: "rubber",
      explode: [-12, 0, 0],
      approx: true,
      lesson:
        "Click to turn on, double-click to power off fully. There is no BOOT button; the power chip drives the boot pin.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [-4.5, -20.35, -1],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -12, 0],
      lesson:
        "USB-C for charging and flashing. It ships with UiFlow2, which turns off USB serial, so the first flash needs a short REPL step.",
    },
    {
      id: "grove",
      name: "HY2.0 (Grove) port",
      kind: "port",
      shape: "box",
      size: [6, 4.5, 4.9],
      position: [6.5, -21.75, -1],
      color: COLORS.caseWhite,
      explode: [0, -12, 0],
      lesson: "A HY2.0 (Grove) port for add-on sensors. Muse does not use it yet.",
    },
    {
      id: "back-shell",
      name: "Back of the case",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 3,
      hollow: { wall: 1.4, floor: "back" },
      size: [24, 48, 12.5],
      position: [0, 0, -1.25],
      color: "#25282c",
      finish: "plastic",
      explode: [0, 0, -30],
      lesson: "The back of the case. A magnet on the back lets the stick cling to metal.",
    },
    printedStandPart({
      deviceId: ID,
      outer,
      usbFace: "bottom",
      explode: [0, -26, -40],
    }),
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.sticks3Shop, FACT_SOURCES.museDevices]),
};
