import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import { printedStandPart } from "../stand";
import type { BoardModel } from "../types";

// 48 x 24 x 13.5 mm orange stick with R3 corners. Same button layout as the
// StickS3 with the large M5 button on the face. Buzzer instead of a speaker.

const ID = "m5stack-stickc-plus2";
const outer = outerFor(ID);

export const m5StickCPlus2: BoardModel = {
  deviceId: ID,
  name: "M5Stack StickC Plus2",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 3,
  parts: [
    {
      id: "front-button",
      name: "M5 button (talk)",
      kind: "button",
      shape: "roundedBox",
      radius: 1.5,
      size: [9, 7, 2],
      position: [0, -14, 5.75],
      color: "#c86f1d",
      finish: "rubber",
      explode: [0, 0, 42],
      lesson: "The front button is push-to-talk under Muse. It also confirms pairing.",
    },
    {
      id: "front-plate",
      name: "Front of the case",
      kind: "shell-front",
      shape: "roundedBox",
      radius: 3,
      size: [24, 48, 2.5],
      position: [0, 0, 5.5],
      cutouts: [
        { shape: "rect", size: [15.5, 26.5], offset: [0, 7], radius: 1 },
        { shape: "rect", size: [10, 8], offset: [0, -14], radius: 1.8 },
      ],
      color: COLORS.orangeCase,
      finish: "plastic",
      explode: [0, 0, 32],
      lesson: "The orange front of the case, with windows for the screen and the M5 button.",
    },
    {
      id: "lcd",
      name: '1.14" color LCD',
      kind: "screen",
      shape: "box",
      size: [14.2, 25.2, 1.4],
      position: [0, 7, 3.55],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 23],
      lesson: "A 1.14 inch color LCD, 135 by 240 pixels. Muse shows its full UI here: avatar, menu and images.",
    },
    {
      id: "esp32",
      name: "ESP32 (2 MB PSRAM)",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-4, -15, 2.1],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 12],
      approx: true,
      lesson:
        "A classic ESP32 with 2 MB of PSRAM runs the full Muse UI. Its 8 MB of flash uses Muse's smaller partition table.",
    },
    {
      id: "usb-bridge",
      name: "CH9102 USB bridge",
      kind: "chip",
      shape: "box",
      size: [4, 4, 1],
      position: [5, -15, 2.1],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 12],
      approx: true,
      lesson: "The CH9102 USB bridge handles flashing. It drops out above 230400 baud, so Muse's flash tool uses that speed.",
    },
    {
      id: "imu",
      name: "Motion sensor (IMU)",
      kind: "sensor",
      shape: "box",
      size: [3, 3, 1],
      position: [5, -20, 2.1],
      color: COLORS.sensor,
      explode: [0, 0, 12],
      approx: true,
      lesson: "A motion sensor (IMU). Muse does not use it yet.",
    },
    {
      id: "rtc",
      name: "Real-time clock",
      kind: "chip",
      shape: "box",
      size: [3, 3, 1],
      position: [-6, -21, 2.1],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 12],
      approx: true,
      lesson: "A real-time clock chip. Muse does not use it yet.",
    },
    {
      id: "mic",
      name: "Microphone",
      kind: "mic",
      shape: "cylinder",
      size: [2.5, 2.5, 1],
      position: [-1, -21, 2.1],
      color: COLORS.mic,
      explode: [0, 0, 12],
      approx: true,
      lesson: "The microphone for push-to-talk.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 2,
      size: [21.5, 45, 1],
      position: [0, 0, 1.1],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 4],
      approx: true,
      lesson: "The main board inside the stick. The chips sit below the screen.",
    },
    {
      id: "ir-tx",
      name: "IR transmitter",
      kind: "led",
      shape: "box",
      size: [3, 3, 2.4],
      position: [-5, 22.5, 3],
      color: "#2b2b30",
      glow: "#ff5a5a",
      explode: [0, 12, 0],
      approx: true,
      lesson: "An infrared transmitter. Muse does not use it yet.",
    },
    {
      id: "hat-header",
      name: "Hat header (8-pin)",
      kind: "port",
      shape: "box",
      size: [20.3, 4, 2.6],
      position: [0, 22, -2],
      color: COLORS.header,
      explode: [0, 14, 0],
      lesson: "An 8-pin header on top for M5Stack Hat add-ons.",
    },
    {
      id: "buzzer",
      name: "Buzzer",
      kind: "speaker",
      shape: "cylinder",
      size: [9, 9, 3],
      position: [0, 12, -0.9],
      color: COLORS.speaker,
      explode: [0, 0, -10],
      approx: true,
      lesson: "A small passive buzzer stands in for a speaker, so any sound is quiet.",
    },
    {
      id: "battery",
      name: "Battery (200 mAh)",
      kind: "battery",
      shape: "roundedBox",
      radius: 1.5,
      size: [20, 20, 4],
      position: [0, -5, -3.3],
      color: COLORS.battery,
      finish: "metal",
      explode: [0, 0, -17],
      approx: true,
      lesson: "A 200 mAh battery. Muse can read its voltage, but not whether it is charging.",
    },
    {
      id: "side-button",
      name: "Side button (menu)",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [1.6, 7, 3],
      position: [11.2, 6, 0],
      color: COLORS.caseDark,
      finish: "rubber",
      explode: [12, 0, 0],
      approx: true,
      lesson: "The side button steps through the menu.",
    },
    {
      id: "power-button",
      name: "Power button",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [1.6, 7, 3],
      position: [-11.2, -12, 0],
      color: COLORS.caseDark,
      finish: "rubber",
      explode: [-12, 0, 0],
      approx: true,
      lesson: "The power button wakes the screen. Hold it for 2 seconds to power off.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [-4.5, -20.35, -1.5],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -12, 0],
      lesson: LESSONS.usbData,
    },
    {
      id: "grove",
      name: "HY2.0 (Grove) port",
      kind: "port",
      shape: "box",
      size: [6, 4.5, 4.9],
      position: [6.5, -21.75, -1.5],
      color: COLORS.caseWhite,
      explode: [0, -12, 0],
      lesson: "A HY2.0 (Grove) port for add-on sensors. Muse does not use it yet.",
    },
    {
      id: "back-shell",
      name: "Back of the case",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 3,
      hollow: { wall: 1.4, floor: "back" },
      size: [24, 48, 11],
      position: [0, 0, -1.25],
      color: COLORS.orangeCase,
      finish: "plastic",
      explode: [0, 0, -28],
      lesson: "The back of the case. M5Stack lists the StickC Plus2 as end of life; the StickS3 replaces it.",
    },
    printedStandPart({
      deviceId: ID,
      outer,
      usbFace: "bottom",
      explode: [0, -26, -38],
    }),
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
