import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";
import { piPcb, piPos } from "./pi-layout";

// Positions and connector heights (Z) from Raspberry Pi's Pi 4 mechanical
// drawing: Ethernet (Z 13.5) and two USB stacks (Z 16.0) down the right
// edge at 45.75 / 27 / 9 mm; USB-C, two micro HDMI and the audio jack on the
// bottom edge; header Z 8.5. Lies flat; +z is the component side.

const ID = "raspberry-pi-4b";
const outer = outerFor(ID);
const TOP = -6.25; // top face of the PCB

export const raspberryPi4b: BoardModel = {
  deviceId: ID,
  name: "Raspberry Pi 4 Model B",
  outer: { ...outer, shape: "board" },
  orientation: "flat",
  cornerRadius: 3,
  parts: [
    piPcb({
      z: TOP - 0.8,
      lesson: "The Raspberry Pi 4 Model B board, 85 by 56 mm. The Muse Linux SDK lists it as supported.",
    }),
    {
      id: "soc",
      name: "Processor (SoC)",
      kind: "chip",
      shape: "box",
      size: [15, 15, 2.4],
      position: piPos(29.2, 32.6, TOP + 1.2),
      color: COLORS.shield,
      finish: "metal",
      explode: [0, 0, 20],
      approx: true,
      lesson: "The main processor. " + LESSONS.piSoc,
    },
    {
      id: "ram",
      name: "Memory (RAM)",
      kind: "chip",
      shape: "box",
      size: [11.6, 15.2, 1.2],
      position: piPos(44.8, 32.5, TOP + 0.6),
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 20],
      approx: true,
      lesson: "The memory chip. Pi 4 boards come with different amounts of memory.",
    },
    {
      id: "wireless",
      name: "Wi-Fi and Bluetooth",
      kind: "antenna",
      shape: "box",
      size: [10.5, 12.9, 1.8],
      position: piPos(12.1, 42.6, TOP + 0.9),
      color: COLORS.shield,
      finish: "metal",
      explode: [0, 0, 20],
      approx: true,
      lesson: "2.4 GHz and 5 GHz Wi-Fi with Bluetooth 5.0 and BLE. " + LESSONS.piPair,
    },
    {
      id: "gpio-header",
      name: "40-pin GPIO header",
      kind: "port",
      shape: "box",
      size: [50.8, 5.08, 8.5],
      position: piPos(32.5, 52.5, TOP + 4.25),
      color: COLORS.header,
      explode: [0, 0, 30],
      lesson: "The standard 40-pin header for HATs, sensors and jumper wires.",
    },
    {
      id: "ethernet",
      name: "Ethernet port",
      kind: "port",
      shape: "box",
      size: [21, 16, 13.5],
      position: piPos(74.5, 45.75, TOP + 6.75),
      color: COLORS.connector,
      finish: "metal",
      explode: [18, 0, 6],
      lesson: "An Ethernet port for a wired network.",
    },
    {
      id: "usb3",
      name: "USB 3.0 ports (2)",
      kind: "port",
      shape: "box",
      size: [17.5, 13.1, 16],
      position: piPos(76.25, 27, TOP + 8),
      color: COLORS.connector,
      finish: "metal",
      explode: [18, 0, 6],
      lesson: "Two USB 3.0 ports for fast drives and adapters.",
    },
    {
      id: "usb2",
      name: "USB 2.0 ports (2)",
      kind: "port",
      shape: "box",
      size: [17.5, 13.1, 16],
      position: piPos(76.25, 9, TOP + 8),
      color: COLORS.connector,
      finish: "metal",
      explode: [18, 0, 6],
      lesson: "Two USB 2.0 ports for keyboards and other small devices.",
    },
    {
      id: "usb-c-power",
      name: "USB-C power input",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [9, 7.5, 3.2],
      position: piPos(11.2, 3.75, TOP + 1.6),
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -14, 6],
      lesson: "Power comes in here. Use a 5.1 V, 3 A USB-C supply.",
    },
    {
      id: "hdmi-0",
      name: "Micro HDMI port 0",
      kind: "port",
      shape: "box",
      size: [7.5, 7, 3],
      position: piPos(26, 3.5, TOP + 1.5),
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -14, 6],
      lesson: "A micro HDMI port, up to 4K at 60 Hz. Muse does not need a screen.",
    },
    {
      id: "hdmi-1",
      name: "Micro HDMI port 1",
      kind: "port",
      shape: "box",
      size: [7.5, 7, 3],
      position: piPos(39.5, 3.5, TOP + 1.5),
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -14, 6],
      lesson: "The second micro HDMI port, for a second display.",
    },
    {
      id: "csi",
      name: "Camera connector (CSI)",
      kind: "port",
      shape: "box",
      size: [3.5, 22, 5.5],
      position: piPos(47, 11.4, TOP + 2.75),
      color: "#efefe9",
      explode: [0, 0, 14],
      approx: true,
      lesson: "A ribbon connector for a Raspberry Pi camera module. No camera comes with the board.",
    },
    {
      id: "audio-jack",
      name: "Audio and video jack",
      kind: "port",
      shape: "box",
      size: [7, 12, 6],
      position: piPos(53.5, 6, TOP + 3),
      color: COLORS.caseBlack,
      explode: [0, -14, 6],
      approx: true,
      lesson: "A 4-pole jack for stereo audio and composite video.",
    },
    {
      id: "dsi",
      name: "Display connector (DSI)",
      kind: "port",
      shape: "box",
      size: [3.7, 22, 5.5],
      position: piPos(3.25, 27.8, TOP + 2.75),
      color: "#efefe9",
      explode: [-12, 0, 10],
      approx: true,
      lesson: "A ribbon connector for a Raspberry Pi display.",
    },
    {
      id: "microsd",
      name: "microSD slot (underside)",
      kind: "port",
      shape: "box",
      size: [15, 14.5, 1.9],
      position: piPos(7.5, 28, -outer.t / 2 + 0.95),
      color: COLORS.connector,
      finish: "metal",
      explode: [-12, 0, -16],
      approx: true,
      lesson: "Raspberry Pi OS boots from a microSD card here. Use one of 16 GB or more.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.pi4Specs, FACT_SOURCES.museLinuxReadme]),
};
