import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";

// Square desk screen: white case, black touch glass, kickstand on the back.
// Port positions follow the catalog note (USB-C and microSD on the bottom
// edge, a second USB-C in the kickstand recess). Inside is simplified.

const ID = "seeed-sensecap-indicator";
const outer = outerFor(ID);

export const senseCapIndicator: BoardModel = {
  deviceId: ID,
  name: "Seeed SenseCAP Indicator (D1 series)",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 8,
  parts: [
    {
      id: "touch-glass",
      name: "Touch glass",
      kind: "glass",
      shape: "roundedBox",
      radius: 7.5,
      size: [91, 95, 1.2],
      position: [0, 0, 8.4],
      color: COLORS.glass,
      finish: "glass",
      explode: [0, 0, 48],
      lesson:
        "Black glass with a touch layer covers the whole front. Muse runs this board as a status screen with images.",
    },
    {
      id: "lcd",
      name: '4" touchscreen (LCD)',
      kind: "screen",
      shape: "box",
      size: [72, 72, 2.2],
      position: [0, 0, 6.7],
      color: COLORS.screenOff,
      finish: "screen",
      display: "status",
      explode: [0, 0, 34],
      lesson: "A 4 inch screen, 480 by 480 pixels. Muse shows a status screen and images here.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-15, 10, 2.7],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 18],
      approx: true,
      lesson: LESSONS.esp32s3,
    },
    {
      id: "rp2040",
      name: "RP2040 sensor chip",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [15, 10, 2.7],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 18],
      approx: true,
      lesson:
        "A second chip, the RP2040, reads the sensors and passes the readings to the ESP32-S3. Muse needs Seeed's stock RP2040 firmware for this.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 6,
      size: [86, 90, 1.6],
      position: [0, 0, 1.4],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 4],
      approx: true,
      lesson: "The main board carries both chips. The screen sits in front of it and the sensors behind it.",
    },
    {
      id: "air-sensors",
      name: "CO2 and tVOC sensors (D1S, D1Pro)",
      kind: "sensor",
      shape: "box",
      size: [12, 12, 6.1],
      position: [28, -30, -2.45],
      color: COLORS.sensor,
      explode: [0, 0, -16],
      approx: true,
      optional: true,
      lesson:
        "The D1S and D1Pro have CO2 and tVOC sensors built in; the plain D1 has none. Muse reads every sensor at once with sensors.read.",
    },
    {
      id: "buzzer",
      name: "Buzzer",
      kind: "speaker",
      shape: "cylinder",
      size: [9, 9, 4],
      position: [-28, -30, -1.4],
      color: COLORS.speaker,
      explode: [0, 0, -16],
      approx: true,
      lesson: "A small buzzer for beeps. There is no microphone or speaker, so this board has no voice features.",
    },
    {
      id: "top-button",
      name: "Top button",
      kind: "button",
      shape: "roundedBox",
      radius: 1,
      size: [8, 3.5, 4],
      position: [30, 46.75, 0],
      color: COLORS.caseLight,
      finish: "rubber",
      explode: [0, 14, 0],
      approx: true,
      lesson: LESSONS.pairButtonHold,
    },
    {
      id: "usb-bottom",
      name: "USB-C port (bottom)",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [-10, -44.85, 0],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -16, 0],
      approx: true,
      lesson:
        "USB-C on the bottom edge, next to the microSD slot. A CH340 bridge makes it show up as /dev/cu.usbserial-* or /dev/ttyUSB* for flashing.",
    },
    {
      id: "microsd",
      name: "microSD slot",
      kind: "port",
      shape: "box",
      size: [12, 9, 1.8],
      position: [10, -44, -2],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -16, 0],
      approx: true,
      lesson: "A microSD card slot on the bottom edge. Muse does not need a card.",
    },
    {
      id: "grove",
      name: "Grove port",
      kind: "port",
      shape: "box",
      size: [8, 6, 5],
      position: [30, -45.5, 0],
      color: COLORS.caseWhite,
      explode: [0, -16, 0],
      approx: true,
      lesson: "Plug the Grove AHT20 sensor from the box in here for temperature and humidity readings.",
    },
    {
      id: "usb-back",
      name: "USB-C port (back)",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 3.2, 7.3],
      position: [0, -20, -5.35],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, 0, -26],
      approx: true,
      lesson: "A second USB-C port sits in the kickstand recess on the back.",
    },
    {
      id: "back-shell",
      name: "Case",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 8,
      hollow: { wall: 2, floor: "back" },
      size: [93, 97, 16.8],
      position: [0, 0, -0.6],
      color: COLORS.caseWhite,
      finish: "plastic",
      explode: [0, 0, -38],
      lesson: "A finished plastic case. A keyhole slot on the back lets you hang it on a wall.",
    },
    {
      id: "kickstand",
      name: "Fold-out kickstand",
      kind: "stand",
      shape: "roundedBox",
      radius: 3,
      size: [50, 40, 1.5],
      position: [0, 10, -8.25],
      color: COLORS.caseLight,
      finish: "plastic",
      explode: [0, -8, -56],
      approx: true,
      lesson: "A kickstand folds out of the back to hold the screen up on a desk.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
