import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import type { BoardModel } from "../types";

// Seeed lists 69 x 65 x 20 mm without saying which side is which, so the
// width/height split is marked approximate in sources.ts. Round 1.45" screen
// on the front with the camera above it, scroll wheel at the top right,
// USB-C on the bottom (power + programming) and the back (power only).

const ID = "seeed-sensecap-watcher";
const outer = outerFor(ID);

export const senseCapWatcher: BoardModel = {
  deviceId: ID,
  name: "Seeed SenseCAP Watcher",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 14,
  parts: [
    {
      id: "front-cover",
      name: "Front cover",
      kind: "shell-front",
      shape: "roundedBox",
      radius: 14,
      size: [69, 65, 3],
      position: [0, 0, 8.5],
      cutouts: [
        { shape: "circle", size: [38.5, 38.5], offset: [0, -4] },
        { shape: "circle", size: [9, 9], offset: [0, 23] },
      ],
      color: COLORS.caseDark,
      finish: "plastic",
      explode: [0, 0, 42],
      lesson: "The front cover, with windows for the round screen and the camera.",
    },
    {
      id: "glass",
      name: "Cover glass and touch layer",
      kind: "glass",
      shape: "cylinder",
      size: [38, 38, 1],
      position: [0, -4, 7.5],
      color: COLORS.glass,
      finish: "glass",
      explode: [0, 0, 33],
      lesson: "Cover glass with a touch layer. In the live camera view, tap the screen to take a photo.",
    },
    {
      id: "lcd",
      name: '1.45" round touchscreen',
      kind: "screen",
      shape: "cylinder",
      size: [36.8, 36.8, 1.2],
      position: [0, -4, 6.4],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 25],
      lesson:
        "A round 1.45 inch touch LCD, 412 by 412 pixels. Muse's desktop simulator uses this same size, so you can work on the UI with no board attached.",
    },
    {
      id: "camera",
      name: "Camera",
      kind: "camera",
      shape: "cylinder",
      size: [8, 8, 6],
      position: [0, 23, 5.8],
      color: COLORS.camera,
      finish: "chip",
      explode: [0, 0, 22],
      approx: true,
      lesson:
        "The camera. With CONFIG_MUSE_WATCHER_CAMERA=y, Muse's camera.capture returns a JPEG. It is powered only while a capture or the live view runs.",
    },
    {
      id: "himax",
      name: "Himax WiseEye2 HX6538",
      kind: "chip",
      shape: "box",
      size: [6, 6, 1],
      position: [0, 13, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 13],
      approx: true,
      lesson: "The Himax WiseEye2 HX6538 is the AI vision chip that drives the camera. Muse uses its existing firmware for captures.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [-14, -8, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 13],
      approx: true,
      lesson:
        "The ESP32-S3 runs Muse, with 32 MB of flash and 8 MB of PSRAM. Back up its nvsfactory partition before the first flash, because Muse overwrites it.",
    },
    {
      id: "usb-bridge",
      name: "CH342 USB bridge",
      kind: "chip",
      shape: "box",
      size: [4, 4, 1],
      position: [14, -20, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 13],
      approx: true,
      lesson:
        "The CH342 USB bridge shows up as two serial ports. The ESP32-S3 console is the second one; the first is the camera chip.",
    },
    {
      id: "mic",
      name: "Microphone",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [-24, -21, 3.3],
      color: COLORS.mic,
      explode: [0, 0, 13],
      approx: true,
      lesson: "The microphone for push-to-talk. Press the wheel and speak.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 10,
      size: [62, 58, 1.2],
      position: [0, 0, 2.2],
      color: COLORS.pcbBlack,
      finish: "pcb",
      explode: [0, 0, 4],
      approx: true,
      lesson: "The main board carries both chips: the ESP32-S3 for Muse and the Himax chip for vision.",
    },
    {
      id: "speaker",
      name: "Speaker",
      kind: "speaker",
      shape: "cylinder",
      size: [18, 18, 5],
      position: [14, -12, -1.3],
      color: COLORS.speaker,
      explode: [0, 0, -12],
      approx: true,
      lesson: "A small speaker. Muse replies arrive as text unless you add your own text-to-speech.",
    },
    {
      id: "battery",
      name: "Battery",
      kind: "battery",
      shape: "roundedBox",
      radius: 2,
      size: [28, 24, 5],
      position: [-15, 6, -4.9],
      color: COLORS.battery,
      finish: "metal",
      explode: [0, 0, -20],
      approx: true,
      lesson: "A built-in battery. Muse shows its charge level on screen.",
    },
    {
      id: "wheel",
      name: "Scroll wheel",
      kind: "button",
      shape: "cylinder",
      axis: "x",
      size: [5, 12, 12],
      position: [27, 25, 0],
      color: COLORS.rubber,
      finish: "rubber",
      explode: [14, 8, 0],
      approx: true,
      lesson: "Press the wheel to talk and turn it to sleep. Double-click it to open the live camera view.",
    },
    {
      id: "usb-bottom",
      name: "USB-C port (bottom)",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [0, -28.85, -2],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -14, 0],
      approx: true,
      lesson:
        "The bottom USB-C does power and programming. Flash it with Muse's paced tool; plain esptool fails on this board.",
    },
    {
      id: "usb-back",
      name: "USB-C port (back)",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 3.2, 7.3],
      position: [16, 14, -6.35],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, 0, -26],
      approx: true,
      lesson: "The USB-C port on the back is for power only.",
    },
    {
      id: "back-shell",
      name: "Back shell",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 14,
      hollow: { wall: 2, floor: "back" },
      size: [69, 65, 17],
      position: [0, 0, -1.5],
      color: COLORS.caseWhite,
      finish: "plastic",
      explode: [0, 0, -36],
      lesson: "The back shell. The Watcher ships with a bracket, a base plate and a 1/4 inch adapter set for mounting.",
    },
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.watcherShop, FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
