import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import { printedStandPart } from "../stand";
import type { BoardModel } from "../types";

// Portrait case from Waveshare's size drawing: 37.60 x 45.20 x 15.00 mm,
// display window 28.70 x 34.94 mm. BOOT, USB-C, PWR and the TF slot sit on
// the right long edge. Inside is simplified.

const ID = "waveshare-esp32-c6-touch-amoled-1-8";
const outer = outerFor(ID);

export const waveshareC6Amoled18: BoardModel = {
  deviceId: ID,
  name: "Waveshare ESP32-C6-Touch-AMOLED-1.8",
  outer: { ...outer, shape: "box" },
  orientation: "upright",
  cornerRadius: 7,
  parts: [
    {
      id: "glass",
      name: "Cover glass and touch layer",
      kind: "glass",
      shape: "roundedBox",
      radius: 6.2,
      size: [36, 43.6, 1.5],
      position: [0, 0, 6.75],
      color: COLORS.glass,
      finish: "glass",
      explode: [0, 0, 36],
      lesson: "Cover glass with a touch layer, so you can tap through Muse's settings screens.",
    },
    {
      id: "amoled",
      name: '1.8" AMOLED',
      kind: "screen",
      shape: "roundedBox",
      radius: 2,
      size: [28.7, 34.94, 1],
      position: [0, 0, 5.5],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 26],
      lesson:
        "A 1.8 inch AMOLED, 368 by 448 pixels. Muse runs its full UI here, but replies scroll past as text and it can't show images.",
    },
    {
      id: "esp32-c6",
      name: "ESP32-C6",
      kind: "chip",
      shape: "box",
      size: [5, 5, 1],
      position: [-5, 6, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 15],
      approx: true,
      lesson:
        "The ESP32-C6 runs Muse. It is a single-core RISC-V chip with Wi-Fi and Bluetooth LE, but no PSRAM, so there is no home-network tunnel.",
    },
    {
      id: "flash",
      name: "16 MB flash memory",
      kind: "chip",
      shape: "box",
      size: [4, 5, 1],
      position: [5, 6, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 15],
      approx: true,
      lesson: "16 MB of flash memory holds the firmware.",
    },
    {
      id: "imu",
      name: "Motion sensor (IMU)",
      kind: "sensor",
      shape: "box",
      size: [2.5, 3, 1],
      position: [-6, -8, 3.3],
      color: COLORS.sensor,
      explode: [0, 0, 15],
      approx: true,
      lesson: "A motion sensor (IMU) that can tell tilt and movement.",
    },
    {
      id: "rtc",
      name: "Real-time clock",
      kind: "chip",
      shape: "box",
      size: [3, 3, 1],
      position: [5, -8, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 0, 15],
      approx: true,
      lesson: "A real-time clock chip that keeps time.",
    },
    {
      id: "mic",
      name: "Microphone",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [-12, -16, 3.3],
      color: COLORS.mic,
      explode: [0, 0, 15],
      approx: true,
      lesson:
        "The microphone. Push-to-talk sends your voice note over the control session, and the reply comes back as text.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "roundedBox",
      radius: 4,
      size: [33.5, 41, 1.2],
      position: [0, 0, 2.2],
      color: COLORS.pcbBlue,
      finish: "pcb",
      explode: [0, 0, 5],
      approx: true,
      lesson: "The main board. The screen, chips, microphone and side buttons all connect here.",
    },
    {
      id: "speaker",
      name: "Speaker",
      kind: "speaker",
      shape: "roundedBox",
      radius: 2,
      size: [15, 11, 3.5],
      position: [0, 10, -1.75],
      color: COLORS.speaker,
      explode: [0, 0, -10],
      approx: true,
      lesson: "A small speaker for sounds.",
    },
    {
      id: "battery",
      name: "Battery (optional)",
      kind: "battery",
      shape: "roundedBox",
      radius: 2,
      size: [20, 16, 4],
      position: [-3, -6, -3.7],
      color: COLORS.battery,
      finish: "metal",
      explode: [0, 0, -19],
      approx: true,
      optional: true,
      lesson: "Room for an optional 3.7 V lithium cell with an MX1.25 plug.",
    },
    {
      id: "boot-button",
      name: "BOOT button (talk)",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [2, 5, 2.5],
      position: [17.8, 14, 0],
      color: COLORS.caseDark,
      finish: "rubber",
      explode: [12, 0, 0],
      approx: true,
      lesson: "BOOT is push-to-talk under Muse. It also confirms pairing.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [7.3, 8.9, 3.2],
      position: [15.15, 2, 0],
      color: COLORS.connector,
      finish: "metal",
      explode: [14, 0, 0],
      lesson: LESSONS.usbData + " It sits on the right edge with the buttons.",
    },
    {
      id: "pwr-button",
      name: "PWR button",
      kind: "button",
      shape: "roundedBox",
      radius: 0.6,
      size: [2, 5, 2.5],
      position: [17.8, -10, 0],
      color: COLORS.caseDark,
      finish: "rubber",
      explode: [12, 0, 0],
      approx: true,
      lesson: "The power button, on the right edge below the USB-C port.",
    },
    {
      id: "microsd",
      name: "microSD (TF) slot",
      kind: "port",
      shape: "box",
      size: [11, 9, 1.4],
      position: [13.3, -17.5, -2.5],
      color: COLORS.connector,
      finish: "metal",
      explode: [14, 0, 0],
      approx: true,
      lesson: "A microSD (TF) card slot on the right edge. Muse does not need a card.",
    },
    {
      id: "case",
      name: "Case",
      kind: "shell-back",
      shape: "roundedBox",
      radius: 7,
      hollow: { wall: 1.8, floor: "back" },
      size: [37.6, 45.2, 13.5],
      position: [0, 0, -0.75],
      color: COLORS.caseBlack,
      finish: "plastic",
      explode: [0, 0, -32],
      lesson: "A black plastic case. Four screws on the back hold the back cover on.",
    },
    printedStandPart({
      deviceId: ID,
      outer,
      usbFace: "right",
      explode: [0, -26, -42],
    }),
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.museDevices, FACT_SOURCES.museEsp32Agents]),
};
