import { LESSONS } from "../lessons";
import { COLORS } from "../palette";
import { FACT_SOURCES, outerFor, sourceUrlsFor } from "../sources";
import { printedStandPart } from "../stand";
import type { BoardModel } from "../types";

// Round CNC aluminium body from Waveshare's size drawing: 55.00 mm case,
// 48.96 mm glass, 43.76 mm active area, 15.05 mm thick. PWR and BOOT sit on
// the right edge at about 2 and 4 o'clock, USB-C at 6 o'clock.

const ID = "waveshare-esp32-s3-touch-amoled-1-75c";
const outer = outerFor(ID);

export const waveshareS3Amoled175c: BoardModel = {
  deviceId: ID,
  name: "Waveshare ESP32-S3-Touch-AMOLED-1.75C (round)",
  outer: { ...outer, shape: "round" },
  orientation: "upright",
  parts: [
    {
      id: "glass",
      name: "Cover glass and touch layer",
      kind: "glass",
      shape: "cylinder",
      size: [48.96, 48.96, 1.5],
      position: [0, 0, 6.775],
      color: COLORS.glass,
      finish: "glass",
      explode: [0, 0, 38],
      lesson: "Cover glass with a CST9217 touch sensor, so you can tap through Muse's settings.",
    },
    {
      id: "amoled",
      name: '1.75" round AMOLED',
      kind: "screen",
      shape: "cylinder",
      size: [43.76, 43.76, 1],
      position: [0, 0, 5.525],
      color: COLORS.screenOff,
      finish: "screen",
      display: "avatar",
      explode: [0, 0, 27],
      lesson:
        "A round 1.75 inch AMOLED, 466 by 466 pixels, driven by a CO5300 chip. Muse shows its animated avatar, settings and images here.",
    },
    {
      id: "esp32-s3",
      name: "ESP32-S3R8",
      kind: "chip",
      shape: "box",
      size: [7, 7, 1],
      position: [0, 6, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [0, 18, 20],
      approx: true,
      lesson:
        "The ESP32-S3R8 runs Muse, with 8 MB of PSRAM. PSRAM is what lets Muse show images and run the home-network tunnel.",
    },
    {
      id: "flash",
      name: "32 MB flash memory",
      kind: "chip",
      shape: "box",
      size: [5, 6, 1],
      position: [-10, 6, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [-14, 10, 20],
      approx: true,
      lesson: "32 MB of flash memory for the firmware. Most full-UI Muse builds need 16 MB or more.",
    },
    {
      id: "power-chip",
      name: "AXP2101 power chip",
      kind: "chip",
      shape: "box",
      size: [5, 5, 1],
      position: [10, 6, 3.3],
      color: COLORS.chip,
      finish: "chip",
      explode: [14, 10, 20],
      approx: true,
      lesson: "The AXP2101 power chip handles USB power and the optional battery.",
    },
    {
      id: "imu",
      name: "QMI8658 motion sensor",
      kind: "sensor",
      shape: "box",
      size: [2.5, 3, 1],
      position: [8, -8, 3.3],
      color: COLORS.sensor,
      explode: [17, -8, 18],
      approx: true,
      lesson: "The QMI8658 is a motion sensor (IMU) that can tell tilt and movement.",
    },
    {
      id: "mic-1",
      name: "Microphone 1",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [-12, 18.5, 3.3],
      color: COLORS.mic,
      explode: [-10, 10, 18],
      approx: true,
      lesson: "One of two microphones in a dual-mic array. Press PWR to talk to Muse.",
    },
    {
      id: "mic-2",
      name: "Microphone 2",
      kind: "mic",
      shape: "cylinder",
      size: [3, 3, 1],
      position: [-12, -18.5, 3.3],
      color: COLORS.mic,
      explode: [-10, -10, 18],
      approx: true,
      lesson: "The second microphone of the dual-mic array.",
    },
    {
      id: "pcb",
      name: "Main board",
      kind: "pcb",
      shape: "cylinder",
      size: [47, 47, 1.2],
      position: [0, 0, 2.2],
      color: COLORS.pcbBlue,
      finish: "pcb",
      explode: [0, 0, 5],
      approx: true,
      lesson: "A round main board that fits the case. The screen, chips and microphones all connect here.",
    },
    {
      id: "speaker",
      name: "Speaker",
      kind: "speaker",
      shape: "cylinder",
      size: [16, 16, 4],
      position: [0, 12, -2],
      color: COLORS.speaker,
      explode: [16, 14, -16],
      approx: true,
      lesson: "A small speaker. Muse replies arrive as text unless you add your own text-to-speech.",
    },
    {
      id: "battery",
      name: "Battery (optional)",
      kind: "battery",
      shape: "roundedBox",
      radius: 2,
      size: [28, 18, 4.5],
      position: [0, -9, -3.1],
      color: COLORS.battery,
      finish: "metal",
      explode: [-14, -13, -24],
      approx: true,
      optional: true,
      lesson:
        "Room for an optional 3.7 V lithium cell with an MX1.25 plug. Waveshare also sells a version with the battery.",
    },
    {
      id: "pwr-button",
      name: "PWR button (talk)",
      kind: "button",
      shape: "roundedBox",
      radius: 0.8,
      size: [2.4, 5, 3],
      position: [25.6, 13.75, 0],
      color: "#969da7",
      finish: "metal",
      explode: [14, 0, 0],
      lesson: "PWR, the upper button on the right edge, is push-to-talk under Muse. Press it to confirm pairing.",
    },
    {
      id: "boot-button",
      name: "BOOT button",
      kind: "button",
      shape: "roundedBox",
      radius: 0.8,
      size: [2.4, 5, 3],
      position: [25.6, -13.75, 0],
      color: COLORS.aluminum,
      finish: "metal",
      explode: [14, 0, 0],
      lesson: "BOOT, the lower button. Flashing tools use it to put the chip into download mode.",
    },
    {
      id: "usb-c",
      name: "USB-C port",
      kind: "port",
      shape: "roundedBox",
      radius: 1.4,
      size: [8.9, 7.3, 3.2],
      position: [0, -23.85, 0],
      color: COLORS.connector,
      finish: "metal",
      explode: [0, -12, 0],
      lesson: LESSONS.usbData,
    },
    {
      id: "usb-c-device-plug",
      name: "Device-side USB-C plug",
      kind: "port",
      shape: "roundedBox",
      radius: 1.2,
      size: [10.5, 7, 4.2],
      position: [0, -29.2, -0.3],
      color: "#22262c",
      finish: "rubber",
      external: true,
      explode: [0, -6, -6],
      lesson: "The required data cable connects here for power and flashing. This plug is shown at its real end of the shortened cable model.",
    },
    {
      id: "usb-c-data-cable",
      name: "USB-C data cable",
      kind: "cable",
      shape: "tube",
      size: [38, 34, 14],
      position: [0, -40, -0.3],
      path: [
        [0, 8, 0],
        [0, 1, 0],
        [-3, -7, -2],
        [-12, -16, -7],
        [-24, -22, -10],
        [-35, -23, -10],
      ],
      thickness: 1.9,
      color: "#242830",
      finish: "rubber",
      explode: [0, -6, -8],
      approx: true,
      external: true,
      lesson: "A USB-C cable with data conductors is required to flash and power the orb. The cable is shown shortened so the whole build stays inspectable.",
    },
    {
      id: "usb-c-host-plug",
      name: "Computer-side USB-C plug",
      kind: "port",
      shape: "roundedBox",
      radius: 1.2,
      size: [10.5, 7, 4.2],
      position: [-38, -63, -10.3],
      color: "#22262c",
      finish: "rubber",
      explode: [-3, -6, -8],
      approx: true,
      external: true,
      lesson: "The other end connects to a computer or USB power source. Use a known data cable, not a charge-only cable.",
    },
    {
      id: "case",
      name: "Aluminum case",
      kind: "shell-back",
      shape: "cylinder",
      hollow: { wall: 2.2, floor: "back" },
      size: [55, 55, 13.55],
      position: [0, 0, -0.75],
      color: "#969da7",
      finish: "metal",
      explode: [0, 0, -34],
      lesson: "A round case machined from aluminum. The buttons sit on its right edge and USB-C at the bottom.",
    },
    printedStandPart({
      deviceId: ID,
      outer,
      usbFace: "bottom",
      explode: [0, -12, -28],
    }),
  ],
  sources: sourceUrlsFor(ID, [FACT_SOURCES.waveshare175c, FACT_SOURCES.museDevices]),
};
